[project]
name = "bsa-venv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "yangfu", email = "yangfu@raisecom.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
bsa-venv = "bsa_venv:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
